### ISSUE TITLE
New version with updated constraint

### ISSUE THREAD

**Issue by michaelsauter** [rudionrails/canonical_dude#2]
Could you release a new version with the updated version constraint? That would be really helpful :)

Otherwise there is no way to upgrade to Rails 4 with `canonical_dude` in the `Gemfile` ...

**Comment by rsmdt** [comment]
You are always able to use the source version in case there is no official gem yet:

```
# in your Gemfile
gem 'canonical_dude', github: 'rudionrails/canonical_dude'
```

Anywho, v2.1.0 is released :-)

**Comment by michaelsauter** [comment]
Sure :) But an official version is much better. Thanks!
